namespaceOverride: ""
rbac:
  create: true
releaseLabel: true
prometheus:
  prometheusSpec:
    scrapeInterval: "120s"
    resources:
      requests:
        cpu: 150m
        memory: 896Mi
      limits:
        cpu: 600m
        memory: 1792Mi
    remoteWrite:
    - url:  http://lgtm-mimir-nginx:80/api/v1/push
    externalLabels:
       environment: mimir
  monitor:
    enabled: true
    interval: ""
    sampleLimit: 0
    targetLimit: 0
    labelLimit: 0
    labelNameLengthLimit: 0
    labelValueLengthLimit: 0
    scrapeTimeout: ""
    proxyUrl: ""
    honorLabels: true
    metricRelabelings: []
    relabelings: []

# For cloud provider environments turn to false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false

grafana:
  enabled: false
  forceDeployDashboards: true

alertmanager:
  enabled: false

